apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-deployment
  labels:
    app: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          image: farukonderbeyazit/todo-server
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: todo-server-service
spec:
  selector:
    app: todo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080